name: xbl1e

on:
  workflow_dispatch:
    inputs:
      ngrok_download_url:
        description: Ngrok Windows (amd64) ZIP
        required: true
        default: https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download ngrok
        run: |
          Invoke-WebRequest `
            -Uri "${{ github.event.inputs.ngrok_download_url }}" `
            -OutFile ngrok.zip
          Expand-Archive ngrok.zip

      - name: Auth ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      - name: Enable RDP + Admin user
        run: |
          Set-ItemProperty `
            -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
            -Name fDenyTSConnections `
            -Value 0

          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

          New-LocalUser "xbl1e" `
            -Password (ConvertTo-SecureString "W1nd0ws-P4ssw0rd-2025!" -AsPlainText -Force) `
            -FullName "xbl1e"

          Add-LocalGroupMember "Remote Desktop Users" "xbl1e"
          Add-LocalGroupMember "Administrators" "xbl1e"

          Set-ItemProperty `
            -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
            -Name UserAuthentication `
            -Value 1

      - name: Start tunnel
        run: |
          Write-Host "--- RDP ---"
          Write-Host "User: xbl1e"
          Write-Host "Pass: W1nd0ws-P4ssw0rd-2025!"
          Write-Host "-----------"
          .\ngrok\ngrok.exe tcp 3389 --log=stdout
